name: Run main.PY every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install Python Packages Requirements
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements
          
    - name: Run main.pyPY
      run: |
        python main.py

    - name: Commit and push changes
      run: |
        git config --local user.email "amirhdevo@gmail.com"
        git config --local user.name "amirhdevo"
        git add .
        git commit -m "Runed main.py"
        git push
