name: Run maivn.PY every3nutes dv21

on:
 
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        required: true
        default: "World"
        
  schedule:
    - cron: '*/5 * * * *'

jobs: 
    run-main:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install Python Packages Requirements
        run: |
            python -m pip install --upgrade pip 
            pip install -r requirements
            
      - name: Run main.py
        run: |
          python workRequestsChannel.py
          
       
      - name: Commit and push changes 
        run: |
            git config --local user.email "amirhdevo@gmail.com"
            git config --local user.name "amirhdevo"
            git add -A
            git branch -m main
            git commit -m "Run main.py"
            git push -f origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CNFG }}
