name: Run rt main.PY every3nutes df 1 5

on:
  schedule:
    - cron: '*/1 * * * *'

jobs: 
    run-main:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install Python Packages Requirements
        run: |
            python -m pip install --upgrade pip 
            
      - name: Run main.pyPY
        run: |
          python main.py
  
      - name: Commit and push changes
        run: |
          git config --local user.email "amirhdevo@gmail.com"
          git config --local user.name "amirhdevo"
          git add .
          git commit -m "Run main.py"
          git push
